version: '3.8'

services:
  diary-api:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379 
      - RabbitMQSettings__Url=amqp://guest:guest@rabbitmq:5672
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:3000 
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped 

  redis:
    image: redis:alpine
    container_name: diary-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: diary-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: unless-stopped

volumes:
  redis_data:
  rabbitmq_data: