services:
  diary-api:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=diary-redis:6379 
      - RabbitMQSettings__Url=amqp://guest:guest@diary-rabbitmq:5672
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-key.json
    volumes:
      - ./DiaryApp.API/firebase-key.json:/app/firebase-key.json:ro
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped 

  redis:
    image: redis:alpine
    container_name: diary-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: diary-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  redis_data:
  rabbitmq_data: